[package]
name = "sdkcore"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["boren1007@qq.com"]
description = "An SDK version manager for full-stack engineers"

[dependencies]
util = {workspace = true}
reqwest = {workspace = true}
anyhow = { workspace = true}
crossterm = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
unicode-width = { workspace = true }
[target.'cfg(windows)'.dependencies]
winreg = { workspace = true}
windows-sys = { workspace = true}