[package]
name = "cli"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["boren1007@qq.com"]
description = "An SDK version manager for full-stack engineers"

[dependencies]
sdkcore = { workspace = true }
util = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true}
